{
 "title": "Estado del sistema FastAPI",
 "tags": [
  "monitoring",
  "fastapi",
  "devops"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Logs de errores (Loki)",
   "type": "logs",
   "gridPos": { "x": 0, "y": 0, "h": 10, "w": 24 },
   "targets": [
    {
     "expr": "{job=~\"errors|cliente\"}"
    }
   ]
  },
  {
   "title": "Total de peticiones HTTP",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 10, "h": 8, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "http_requests_total" }
   ]
  },
  {
   "title": "Uso de CPU (%)",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 18, "h": 6, "w": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "custom_cpu_percent" }
   ]
  },
  {
   "title": "Uso de RAM (%)",
   "type": "gauge",
   "gridPos": { "x": 8, "y": 18, "h": 6, "w": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "custom_memory_percent" }
   ]
  },
  {
   "title": "Uso de Disco (%)",
   "type": "gauge",
   "gridPos": { "x": 16, "y": 18, "h": 6, "w": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "custom_disk_usage_percent" }
   ]
  },
  {
   "title": "Solicitudes HTTP por endpoint (cliente)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "h": 8, "w": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "http_requests_total" }
   ]
  }
 ]
}